import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

/**
 * Keeps the served editor fresh: `public/editor.html` is GENERATED by the
 * editor workspace (`npm run -w editor build`), so `serve` rebuilds it when
 * it is missing or older than the editor sources. A build failure never
 * stops the server — the phone flow must keep working, the editor URL just
 * 404s with a logged reason. The SEA skips all of this (assets are baked;
 * there is no editor/ next to an installed executable).
 *
 * @module
 */

/** Injection points for {@link ensureEditorBuilt}. */
export interface EditorBuildDeps {
  /** The checkout root (appDir) — where editor/ and public/ live. */
  root: string;
  log: (line: string) => void;
  /** Runs the build; tests inject a recorder. Must throw on failure. */
  exec?: (cmd: string, opts: { cwd: string }) => void;
  /** True inside the single executable: never build, assets are baked. */
  isSea?: boolean;
  /** `--public <dir>`: the user brought their own assets — never build. */
  publicDir?: string;
}

/** Newest mtime (ms) under a file or directory tree; 0 when absent. */
export function newestMtime(p: string): number {
  try {
    const st = fs.statSync(p);
    if (!st.isDirectory()) return st.mtimeMs;
    let newest = st.mtimeMs;
    for (const entry of fs.readdirSync(p)) {
      const m = newestMtime(path.join(p, entry));
      if (m > newest) newest = m;
    }
    return newest;
  } catch {
    return 0;
  }
}

/** Everything a rebuild must react to — includes the bundled shared modules. */
const SOURCES = [
  ["editor", "src"],
  ["editor", "editor.html"],
  ["editor", "vite.config.ts"],
  ["editor", "package.json"],
  ["public", "math.js"],
  ["public", "transport.js"],
];

/** Decides whether `serve` should run the editor build, and why. */
export function editorBuildPlan(root: string): { build: boolean; reason: string } {
  const out = path.join(root, "public", "editor.html");
  const haveOut = fs.existsSync(out);
  if (!fs.existsSync(path.join(root, "editor")))
    return {
      build: false,
      reason: haveOut
        ? "editor: sources absent — serving the existing build"
        : "editor: source directory not found — /editor.html unavailable",
    };
  if (!haveOut) return { build: true, reason: "editor: not built yet" };
  const outM = newestMtime(out);
  const srcM = Math.max(...SOURCES.map((parts) => newestMtime(path.join(root, ...parts))));
  if (srcM > outM) return { build: true, reason: "editor: sources changed" };
  return { build: false, reason: "editor: up to date" };
}

/**
 * Builds the editor when stale, logging what happened. NEVER throws: the
 * server must start regardless of the editor's build health.
 */
export function ensureEditorBuilt(d: EditorBuildDeps): void {
  if (d.isSea) return;
  if (d.publicDir) {
    if (!fs.existsSync(path.join(d.publicDir, "editor.html")))
      d.log("editor: no editor.html in the --public dir — /editor.html will 404");
    return;
  }
  const plan = editorBuildPlan(d.root);
  if (!plan.build) {
    if (plan.reason.includes("unavailable")) d.log(plan.reason);
    return;
  }
  d.log(`${plan.reason} — building (npm run -w editor build)`);
  try {
    const exec =
      d.exec ??
      ((cmd: string, opts: { cwd: string }) => execSync(cmd, { ...opts, stdio: "inherit" }));
    exec("npm run -w editor build", { cwd: d.root });
    d.log("editor: built -> public/editor.html");
  } catch (e) {
    const first = String((e as Error).message ?? e).split(/\r?\n/)[0];
    d.log(
      `editor: build failed — ${first}; serving anyway (/editor.html will 404). ` +
        "Fix with: npm run -w editor build",
    );
  }
}
